"""
Migration: create_collection_transactions
Created: 2025-11-04 15:56:56

Creates the 'transactions' collection with schema validations:
- ID: automatically generated by MongoDB (_id)
- Amount: Decimal, required, greater than 0
- Currency: Enum (USD, EUR, MXN, etc.), required
- Transaction date: required, cannot be in the future
- Category: String, optional (ALIMENTOS, ENTRETENIMIENTO, SALUD, etc.)
- created_at: automatic timestamp
"""

from nauta_migrations.migrate import BaseMigration


class Migration(BaseMigration):
    """Create transactions collection with validations"""
    
    def upgrade(self):
        """
        Create the 'transactions' collection with schema validation.
        """
        collection_name = "transactions"
        
        # Schema validation using $jsonSchema combined with $expr for dynamic date validation
        validator = {
            "$and": [
                {
                    "$jsonSchema": {
                        "bsonType": "object",
                        "required": ["amount", "currency", "transaction_date", "created_at"],
                        "properties": {
                            "_id": {
                                "bsonType": "objectId",
                                "description": "ID automatically generated by MongoDB"
                            },
                            "amount": {
                                "bsonType": "decimal",
                                "description": "Transaction amount (required, must be greater than 0)",
                                "minimum": 0
                            },
                            "currency": {
                                "enum": ["USD", "EUR", "MXN", "GBP", "JPY", "CAD", "AUD", "CHF", "CNY", "BRL"],
                                "description": "Transaction currency (required)",
                            },
                            "transaction_date": {
                                "bsonType": "date",
                                "description": "Transaction date (required, cannot be in the future)"
                            },
                            "category": {
                                "bsonType": "string",
                                "description": "Transaction category (optional)"
                            },
                            "created_at": {
                                "bsonType": "date",
                                "description": "Document creation date and time - datetime (required)"
                            }
                        }
                    }
                },
                {
                    "$expr": {
                        "$lte": ["$transaction_date", "$$NOW"]
                    }
                }
            ]
        }
        
        # Create collection with validation
        # Note: MongoDB 3.6+ supports schema validation
        try:
            # Check if collection already exists
            if collection_name in self.db.list_collection_names():
                print(f"Collection '{collection_name}' already exists. Skipping creation.")
                return
            
            # Create collection with validation
            self.db.create_collection(
                collection_name,
                validator=validator,
                validationLevel="strict",  # Apply validation to all documents
                validationAction="error"   # Reject documents that don't comply
            )
            
            print(f"✓ Collection '{collection_name}' created successfully with validations")
            
        except Exception as e:
            print(f"✗ Error creating collection '{collection_name}': {e}")
            raise
    
    def downgrade(self):
        """
        Drop the 'transactions' collection.
        """
        collection_name = "transactions"
        
        try:
            if collection_name in self.db.list_collection_names():
                self.db.drop_collection(collection_name)
                print(f"✓ Collection '{collection_name}' dropped successfully")
            else:
                print(f"Collection '{collection_name}' does not exist. Nothing to drop.")
        except Exception as e:
            print(f"✗ Error dropping collection '{collection_name}': {e}")
            raise
